/**
 * Font Awesome Library Setup
 * 
 * Centralizes FA icon imports and library configuration.
 * Import this file once in main.tsx to register all icons globally.
 */
import { library } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';

// Prevent FA from auto-adding CSS (we import it above instead)
config.autoAddCss = false;

// ─── Solid Icons ───────────────────────────────────────────────────────────────
import {
  faHouse,
  faGaugeHigh,
  faPlane,
  faHeart,
  faUser,
  faRobot,
  faArrowRightFromBracket,
  faGlobe,
  faChevronDown,
  faMagnifyingGlass,
  faCalendar,
  faCalendarDays,
  faReceipt,
  faPlus,
  faDollarSign,
  faArrowTrendUp,
  faBullseye,
  faCommentDots,
  faCreditCard,
  faShield,
  faCircleCheck,
  faCircleExclamation,
  faLock,
  faWallet,
  faBuilding,
  faMobileScreen,
  faArrowUpRightFromSquare,
  faStar,
  faTrashCan,
  faPaperPlane,
  faSpinner,
  faLocationDot,
  faTriangleExclamation,
  faCircleQuestion,
  faMapLocationDot,
  faCompass,
  faArrowRight,
  faArrowLeft,
  faCheck,
  faXmark,
  faPen,
  faCamera,
  faBars,
  faSun,
  faMoon,
  faLanguage,
  faMoneyBill,
  faShieldHalved,
  faChevronRight,
  faChevronLeft,
  faEye,
  faEyeSlash,
  faCircleInfo,
  faGear,
  faUsers,
  faChartLine,
  faDownload,
  faFilter,
  faSort,
  faEllipsisVertical,
  faImage,
  faPalette,
  faMountain,
  faUmbrellaBeach,
  faCity,
  faPersonHiking,
  faLandmark,
  faMusic,
  faTicket,
  faClock,
  faSliders,
  faBan,
  faPiggyBank,
  faHandHoldingDollar,
  faBookOpen,
  faCirclePlay,
  faEnvelope,
  faPhone,
  faIdCard,
  faBell,
  faBellSlash,
  faTrophy,
  faChevronUp,
  faGripVertical,
  faLeaf,
  faRoute,
  faTableColumns,
  faSquarePlus,
  faCopy,
  faClipboard,
  faRotate,
  faSeedling,
  faFire,
  faSnowflake,
  faChartPie,
  faDatabase,
  faUserShield,
  faRightFromBracket,
  faUpRightAndDownLeftFromCenter,
  faBoltLightning,
  faWandMagicSparkles,
  faHandshake,
  faRankingStar,
  faFileLines,
  faCircle,
  faSquare,
} from '@fortawesome/free-solid-svg-icons';

// ─── Regular Icons ─────────────────────────────────────────────────────────────
import {
  faHeart as farHeart,
  faStar as farStar,
  faCalendar as farCalendar,
  faClock as farClock,
  faCircle as farCircle,
  faSquare as farSquare,
  faBell as farBell,
  faBookmark as farBookmark,
  faEye as farEye,
  faEnvelope as farEnvelope,
} from '@fortawesome/free-regular-svg-icons';

// ─── Brand Icons ───────────────────────────────────────────────────────────────
import {
  faGoogle,
  faYoutube,
  faInstagram,
  faXTwitter,
  faFacebook,
  faTiktok,
  faPinterest,
  faPaypal,
} from '@fortawesome/free-brands-svg-icons';

// Register all icons with the library
library.add(
  // Solid
  faHouse, faGaugeHigh, faPlane, faHeart, faUser, faRobot,
  faArrowRightFromBracket, faGlobe, faChevronDown, faMagnifyingGlass,
  faCalendar, faCalendarDays, faReceipt, faPlus, faDollarSign,
  faArrowTrendUp, faBullseye, faCommentDots, faCreditCard, faShield,
  faCircleCheck, faCircleExclamation, faLock, faWallet, faBuilding,
  faMobileScreen, faArrowUpRightFromSquare, faStar, faTrashCan,
  faPaperPlane, faSpinner, faLocationDot, faTriangleExclamation,
  faCircleQuestion, faMapLocationDot, faCompass, faArrowRight, faArrowLeft,
  faCheck, faXmark, faPen, faCamera, faBars, faSun, faMoon, faLanguage,
  faMoneyBill, faShieldHalved, faChevronRight, faChevronLeft, faEye,
  faEyeSlash, faCircleInfo, faGear, faUsers, faChartLine, faDownload,
  faFilter, faSort, faEllipsisVertical, faImage, faPalette, faMountain,
  faUmbrellaBeach, faCity, faPersonHiking, faLandmark, faMusic, faTicket,
  faClock, faSliders, faBan, faPiggyBank, faHandHoldingDollar, faBookOpen,
  faCirclePlay, faEnvelope, faPhone, faIdCard, faBell, faBellSlash,
  faTrophy, faChevronUp, faGripVertical, faLeaf, faRoute, faTableColumns,
  faSquarePlus, faCopy, faClipboard, faRotate, faSeedling, faFire,
  faSnowflake, faChartPie, faDatabase, faUserShield, faRightFromBracket,
  faUpRightAndDownLeftFromCenter, faBoltLightning, faWandMagicSparkles,
  faHandshake, faRankingStar, faFileLines, faCircle, faSquare,
  // Regular
  farHeart, farStar, farCalendar, farClock, farCircle, farSquare,
  farBell, farBookmark, farEye, farEnvelope,
  // Brands
  faGoogle, faYoutube, faInstagram, faXTwitter, faFacebook, faTiktok,
  faPinterest, faPaypal,
);
